runs:
  using: composite
  steps:
    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install yarn
      run: npm install -g yarn
      shell: bash
    - name: Enable Corepack
      run: corepack enable
      shell: bash
    - name: Cache
      uses: actions/cache@v4
      id: cache
      with:
        path: '**/node_modules'
        key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
    - name: Install
      working-directory: ${{ inputs.working-directory }}
      run: yarn --immutable
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
